// <auto-generated />
namespace ShoesShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_image_shoe_atribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_image_shoe_atribute));
        
        string IMigrationMetadata.Id
        {
            get { return "201804060041562_add_image_shoe_atribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
