// <auto-generated />
namespace ShoesShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_relationship_to_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_relationship_to_image));
        
        string IMigrationMetadata.Id
        {
            get { return "201804050145559_add_relationship_to_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
