// <auto-generated />
namespace ShoesShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_atributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_atributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201804050425554_update_atributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
